### ISSUE TITLE
Best way to combine models parameters with evals

### ISSUE THREAD

**Issue by adw96** [jacobbien/simulator#4]
Hi everyone -- I was looking for an easier way to combine information about the model parameters for each simulation with the resulting `data.frame(evals)` object, and @jacobbien kindly suggested the following easy solution that I'm posting here for the benefit of others who may want this functionality. 

For a simulation called `sim,` you can access the model information in the following way 
```
ev_df <- sim %>% evals %>% as.data.frame
model_df <- sim %>% model %>% as.data.frame
ev_with_model_params <- dplyr::right_join(model_df, ev_df, by = c("name" = "Model"))
```

In particular, the columns of `model_df` contain the model parameters, saving you from string processing `ev_df$Model` to get the model parameters. 

Hope this helps someone and many thanks to @jacobbien for providing this solution!

**Comment by jacobbien** [comment]
Thanks @adw96 for putting this here for others who might be looking for this functionality!
