### ISSUE TITLE
Error: sha1() has no method for the [phyloseq] class 

### ISSUE THREAD

**Issue by adw96** [jacobbien/simulator#9]
Hi fellow simulator users - posting an issue and a workaround to save time for others. If you are working with models that take in S4 objects, you may get the error `Error: sha1() has no method for the [...] class`. For example, I was running something like

```
new_simulation("Fancy Sim", "my-sim") %>%
  generate_model(my_model, 
                 ps = my_nonstandard_S4_object, 
                 sig_sq = as.list(seq(0, 10, length.out = 11)),
                 vary_along = "sig_sq") %>%
  simulate_from_model(nsim = 10)
```

and my error was `Error: sha1() has no method for the 'phyloseq' class`. 

The specific line that fails in `simulator` is `digest::sha1(nonstandard_S4_object)`, which, as far as I can tell, is used to create  unique identifiers for each draw from the model. If your S4 object doesn't have a representation using `digest::sha1`, your `simulator` code will fail. 

In my case, I could convert a `phyloseq` S4 object to a tibble/data frame using `speedyseq::as_tibble` a la

```
new_simulation("Fancy Sim", "my-sim") %>%
  generate_model(my_model_v2, 
                 ps = my_nonstandard_S4_object %>% speedyseq::as_tibble, 
                 sig_sq = as.list(seq(0, 10, length.out = 11)),
                 vary_along = "sig_sq") %>%
  simulate_from_model(nsim = 10)
```

and this worked fine (with a corresponding modification to `my_model`). 

Hope this helps others - I had no idea what `sha1()` was and had to do some digging, so I hope this saves you some time 😸

**Comment by jacobbien** [comment]
Thanks @adw96 for the good point and helpful comment! Yes, here `sha1` is used to map objects to unique strings to be used in file naming.  The idea is that if anything ever changes within that object, it should be considered a different model.  As you point out, apparently sha1 doesn't know what to do with arbitrary S4 objects.

For those interested to know more about file naming, the [James-Stein vignette](http://faculty.bscb.cornell.edu/~bien/simulator_vignettes/js.html) has a footnote that gives a bit more info.
